---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest

  - name: update repository dnf
    dnf:
      update_cache: yes

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
